<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $now = Carbon::now();

        // ─────────────────────────────────────────────
        //  USUARIOS
        // ─────────────────────────────────────────────
        User::firstOrCreate(
            ['email' => 'admin@gmail.com'],
            [
                'nombre'        => 'Juan Pérez',
                'password'      => bcrypt('admin123'),
                'rol'           => 'ADMIN',
                'activo'        => true,
                'direccion'     => 'Calle Principal 123, Corrientes',
                'telefono'      => '3794123456',
                'codigo_postal' => '3400',
            ]
        );

        User::firstOrCreate(
            ['email' => 'usuario@gmail.com'],
            [
                'nombre'        => 'Usuario X',
                'password'      => bcrypt('usuario123'),
                'rol'           => 'CLIENTE',
                'activo'        => true,
                'direccion'     => 'Av. Libertad 456, Corrientes',
                'telefono'      => '3794654321',
                'codigo_postal' => '3400',
            ]
        );

        // ─────────────────────────────────────────────
        //  CATEGORÍAS (Se eliminó Consolas y Periféricos)
        // ─────────────────────────────────────────────
        $categorias = [
            ['id' => 1,  'nombre' => 'RPG',             'descripcion' => 'Juegos de rol'],
            ['id' => 2,  'nombre' => 'Plataformas',     'descripcion' => 'Juegos de plataformas'],
            ['id' => 3,  'nombre' => 'Survival Horror', 'descripcion' => 'Juegos de terror y supervivencia'],
            ['id' => 4,  'nombre' => 'Carreras',        'descripcion' => 'Juegos de carreras'],
            ['id' => 5,  'nombre' => 'Deportes',        'descripcion' => 'Juegos deportivos'],
            ['id' => 6,  'nombre' => 'Estrategia',      'descripcion' => 'Juegos de estrategia'],
            ['id' => 7,  'nombre' => 'Lucha',           'descripcion' => 'Juegos de lucha'],
            ['id' => 8,  'nombre' => 'Aventura',        'descripcion' => 'Juegos de aventura'],
            ['id' => 9,  'nombre' => 'Puzzle',          'descripcion' => 'Juegos de puzzle'],
        ];

        foreach ($categorias as $cat) {
            DB::table('categorias')->insert([
                ...$cat,
                'activo'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ]);
        }

        // ─────────────────────────────────────────────
        //  PRODUCTOS — JUEGOS
        // ─────────────────────────────────────────────
        $juegos = [
            [
                'id_categoria'         => 3,
                'nombre'               => 'Resident Evil Director\'s Cut',
                'descripcion'          => 'Videojuego survival horror.',
                'precio_original'      => 169000.00,
                'precio'               => 143650.00,
                'porcentaje_descuento' => 15,
                'stock'                => 3,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/dJW5Fp4z/REDC-USA.webp',
                'marca'                => 'Capcom',
                'consola'              => 'PlayStation 1',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Metal Gear Solid 1',
                'descripcion'          => 'Videojuego de acción y aventura.',
                'precio_original'      => 100000.00,
                'precio'               => 70000.00,
                'porcentaje_descuento' => 30,
                'stock'                => 2,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/27GwrW2K/ps1-metalgearsolid-front-eu-thumb.jpg',
                'marca'                => 'Konami',
                'consola'              => 'PlayStation 1',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'LSD Dream Emulator',
                'descripcion'          => 'Videojuego de exploración.',
                'precio_original'      => 95000.00,
                'precio'               => 80750.00,
                'porcentaje_descuento' => 15,
                'stock'                => 3,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/DH2kcCqH/cover-lsd.png',
                'marca'                => 'Asmik Ace',
                'consola'              => 'PlayStation 1',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 3,
                'nombre'               => 'Silent Hill 2',
                'descripcion'          => 'Videojuego survival horror.',
                'precio_original'      => 110000.00,
                'precio'               => 77000.00,
                'porcentaje_descuento' => 30,
                'stock'                => 4,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/cKkMthnn/c4007fff-9166-4389-83b6-e338c2278a29.jpg',
                'marca'                => 'Konami',
                'consola'              => 'PlayStation 2',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 1,
                'nombre'               => 'Shin Megami Tensei Persona 4',
                'descripcion'          => 'Videojuego RPG.',
                'precio_original'      => 180000.00,
                'precio'               => 180000.00,
                'porcentaje_descuento' => 0,
                'stock'                => 5,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/tTW6mCxn/88dd3c72-663f-4262-a85d-0ba96f2a99ab.jpg',
                'marca'                => 'Atlus',
                'consola'              => 'PlayStation 2',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Castlevania: Symphony of the Night',
                'descripcion'          => 'Videojuego de acción y aventura (Metroidvania).',
                'precio_original'      => 195000.00,
                'precio'               => 165750.00,
                'porcentaje_descuento' => 15,
                'stock'                => 6,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/3mfHFSWX/r2-bcde5969-75c3-41d5-9c23-0de7f3c50235.png',
                'marca'                => 'Konami',
                'consola'              => 'PlayStation 1',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Pokémon Rojo',
                'descripcion'          => 'Videojuego rpg.',
                'precio_original'      => 55556.00,
                'precio'               => 50000.40,
                'porcentaje_descuento' => 10,
                'stock'                => 5,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/WpDVmnCM/7b8101cd-ea45-4189-b9e6-45e170aa42dc.png',
                'marca'                => 'Nintendo',
                'consola'              => 'Game Boy',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'God of War II',
                'descripcion'          => 'Videojuego de acción y aventura.',
                'precio_original'      => 55000.00,
                'precio'               => 41250.00,
                'porcentaje_descuento' => 25,
                'stock'                => 9,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/rgXtdKt/2b06034c-9d15-4bdd-8e20-b564027cd957.jpg',
                'marca'                => 'Sony',
                'consola'              => 'PlayStation 2',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Devil May Cry',
                'descripcion'          => 'Videojuego hack and slash.',
                'precio_original'      => 105000.00,
                'precio'               => 105000.00,
                'porcentaje_descuento' => 0,
                'stock'                => 8,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/ycnz5J5X/a4fecfd9-a573-4045-9d0f-af59709f72ce.jpg',
                'marca'                => 'Capcom',
                'consola'              => 'PlayStation 2',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Star Wars Lethal Alliance',
                'descripcion'          => 'Videojuego de acción y aventura.',
                'precio_original'      => 14900.00,
                'precio'               => 10430.00,
                'porcentaje_descuento' => 30,
                'stock'                => 8,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/1G4JPgGj/89a8e3a4-ef6a-421d-bc26-22e0ede9b06f.png',
                'marca'                => 'Ubisoft',
                'consola'              => 'Nintendo DS',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 4,
                'nombre'               => 'Gran Turismo 4',
                'descripcion'          => 'Juego de carreras de autos.',
                'precio_original'      => 15000.00,
                'precio'               => 11250.00,
                'porcentaje_descuento' => 25,
                'stock'                => 10,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/21SZ3b9Y/c7df3e76-b752-4d02-a358-841da5cb244d.jpg',
                'marca'                => 'Sony',
                'consola'              => 'PlayStation 2',
                'condicion'            => 'reacondicionado',
            ],
            [
                'id_categoria'         => 1,
                'nombre'               => 'EverGrace',
                'descripcion'          => 'Juego RPG.',
                'precio_original'      => 12000.00,
                'precio'               => 9000.00,
                'porcentaje_descuento' => 25,
                'stock'                => 4,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/Q7s9vgRf/a7491b58-b669-4635-aa4b-520193580f70.jpg',
                'marca'                => 'FromSoftware',
                'consola'              => 'PlayStation 2',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 1,
                'nombre'               => 'Chrono Trigger',
                'descripcion'          => 'Juego RPG.',
                'precio_original'      => 120000.00,
                'precio'               => 90000.00,
                'porcentaje_descuento' => 25,
                'stock'                => 10,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/9m7w7PBD/5db08b42-02db-4a10-b073-6a44abf60720.jpg',
                'marca'                => 'Square',
                'consola'              => 'SNES',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 1,
                'nombre'               => 'Parasite Eve',
                'descripcion'          => 'Videojuego de rol.',
                'precio_original'      => 45000.00,
                'precio'               => 38250.00,
                'porcentaje_descuento' => 15,
                'stock'                => 4,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/vCd79H4p/420ea16a-f054-4952-bfbc-0c4da8655b75.jpg',
                'marca'                => 'Square',
                'consola'              => 'PlayStation 1',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 1,
                'nombre'               => 'Mega Man Battle Network',
                'descripcion'          => 'Videojuego de rol.',
                'precio_original'      => 50000.00,
                'precio'               => 45000.00,
                'porcentaje_descuento' => 10,
                'stock'                => 5,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/FLk8s46K/ee260313-fb62-4596-8af4-cf139c6681d8.png',
                'marca'                => 'Capcom',
                'consola'              => 'Game Boy Advance',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Super Metroid',
                'descripcion'          => 'Videojuego de acción y aventura.',
                'precio_original'      => 80000.00,
                'precio'               => 72000.00,
                'porcentaje_descuento' => 10,
                'stock'                => 3,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/Z654VG2Q/cb1c9cdf-02f9-44e2-a04f-3ec45a9b8cb2.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'SNES',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 2,
                'nombre'               => 'Super Mario 64',
                'descripcion'          => 'Juego de plataformas.',
                'precio_original'      => 165000.00,
                'precio'               => 148500.00,
                'porcentaje_descuento' => 10,
                'stock'                => 5,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/gLF1LCnq/7626b423-054f-4261-9fba-16067cf1e9a3.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'Nintendo 64',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 3,
                'nombre'               => 'Silent Hill 3',
                'descripcion'          => 'Juego de survival horror.',
                'precio_original'      => 145000.00,
                'precio'               => 116000.00,
                'porcentaje_descuento' => 20,
                'stock'                => 5,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/m3k34CZ/a1829960-26a1-433c-adae-856290481792.png',
                'marca'                => 'Konami',
                'consola'              => 'PlayStation 2',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'The Legend of Zelda: Majoras Mask',
                'descripcion'          => 'Videojuego de acción y aventura.',
                'precio_original'      => 150000.00,
                'precio'               => 150000.00,
                'porcentaje_descuento' => 0,
                'stock'                => 4,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/vvYt4xKj/1c277b77-666d-4368-9d17-52a46c020ca4.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'Nintendo 64',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 1,
                'nombre'               => 'Final Fantasy VII',
                'descripcion'          => 'Videojuego de rol.',
                'precio_original'      => 120000.00,
                'precio'               => 102000.00,
                'porcentaje_descuento' => 15,
                'stock'                => 6,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/qF5NjgYq/r2-809dbd84-313e-4408-94f3-726899fe26c4.jpg',
                'marca'                => 'Square',
                'consola'              => 'PlayStation 1',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 2,
                'nombre'               => 'Sonic the Hedgehog 2',
                'descripcion'          => 'Videojuego de plataformas.',
                'precio_original'      => 40000.00,
                'precio'               => 36000.00,
                'porcentaje_descuento' => 10,
                'stock'                => 8,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/67P5CwY9/54506801-806f-4e4a-976d-876c4ea02420.jpg',
                'marca'                => 'Sega',
                'consola'              => 'Sega Genesis',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 2,
                'nombre'               => 'Crash Bandicoot',
                'descripcion'          => 'Videojuego de plataformas.',
                'precio_original'      => 90000.00,
                'precio'               => 81000.00,
                'porcentaje_descuento' => 10,
                'stock'                => 5,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/fG99b4rp/251b3973-c46c-4c4c-b46a-b34bcd23c860.jpg',
                'marca'                => 'Naughty Dog',
                'consola'              => 'PlayStation 1',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 7,
                'nombre'               => 'Street Fighter II',
                'descripcion'          => 'Videojuego de lucha.',
                'precio_original'      => 50000.00,
                'precio'               => 45000.00,
                'porcentaje_descuento' => 10,
                'stock'                => 7,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/nqSD8x3q/78dc0ce0-132e-432e-bee9-8fda6b7deb93.jpg',
                'marca'                => 'Capcom',
                'consola'              => 'SNES',
                'condicion'            => 'usado',
            ],
        ];

        foreach ($juegos as $juego) {
            DB::table('productos')->insert([
                ...$juego,
                'tipo_producto' => 'videojuego',
                'activo'        => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ]);
        }

        // ─────────────────────────────────────────────
        //  PRODUCTOS — CONSOLAS (Precios normalizados a ARS)
        // ─────────────────────────────────────────────
        $consolas = [
            [
                'id_categoria'         => 8,
                'nombre'               => 'Nintendo Entertainment System',
                'descripcion'          => 'Consola clásica de 8 bits.',
                'precio_original'      => 100000.00,
                'precio'               => 80000.00,
                'porcentaje_descuento' => 20,
                'stock'                => 15,
                'stock_bajo'           => 5,
                'url_imagen'           => 'https://i.ibb.co/s9fgMLjR/Nitendo-entertainment-system.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'NES',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Super Nintendo',
                'descripcion'          => 'Consola de 16 bits de Nintendo.',
                'precio_original'      => 150000.00,
                'precio'               => 120000.00,
                'porcentaje_descuento' => 20,
                'stock'                => 10,
                'stock_bajo'           => 3,
                'url_imagen'           => 'https://i.ibb.co/PsWZCq5x/s-l1200.webp',
                'marca'                => 'Nintendo',
                'consola'              => 'SNES',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Sega Genesis',
                'descripcion'          => 'Consola de 16 bits de Sega.',
                'precio_original'      => 120000.00,
                'precio'               => 90000.00,
                'porcentaje_descuento' => 25,
                'stock'                => 20,
                'stock_bajo'           => 5,
                'url_imagen'           => 'https://i.ibb.co/RG4Tq6Lh/segagenesis.jpg',
                'marca'                => 'Sega',
                'consola'              => 'Sega Genesis',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'PlayStation 1',
                'descripcion'          => 'Primera consola de Sony.',
                'precio_original'      => 80000.00,
                'precio'               => 60000.00,
                'porcentaje_descuento' => 25,
                'stock'                => 30,
                'stock_bajo'           => 10,
                'url_imagen'           => 'https://i.ibb.co/fzWm6WwG/image.png',
                'marca'                => 'Sony',
                'consola'              => 'PlayStation 1',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Nintendo 64',
                'descripcion'          => 'Consola de 64 bits de Nintendo.',
                'precio_original'      => 180000.00,
                'precio'               => 150000.00,
                'porcentaje_descuento' => 16,
                'stock'                => 8,
                'stock_bajo'           => 2,
                'url_imagen'           => 'https://i.ibb.co/8gcHMnqr/image.png',
                'marca'                => 'Nintendo',
                'consola'              => 'Nintendo 64',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Sega Dreamcast',
                'descripcion'          => 'Última consola de Sega.',
                'precio_original'      => 200000.00,
                'precio'               => 160000.00,
                'porcentaje_descuento' => 20,
                'stock'                => 5,
                'stock_bajo'           => 2,
                'url_imagen'           => 'https://i.ibb.co/rR0WS5cF/image.png',
                'marca'                => 'Sega',
                'consola'              => 'Dreamcast',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Game Boy',
                'descripcion'          => 'Consola portátil de Nintendo.',
                'precio_original'      => 90000.00,
                'precio'               => 70000.00,
                'porcentaje_descuento' => 22,
                'stock'                => 25,
                'stock_bajo'           => 8,
                'url_imagen'           => 'https://i.ibb.co/mFcCSWct/image.png',
                'marca'                => 'Nintendo',
                'consola'              => 'Game Boy',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Atari 2600',
                'descripcion'          => 'Pionera en consolas de videojuegos.',
                'precio_original'      => 110000.00,
                'precio'               => 85000.00,
                'porcentaje_descuento' => 22,
                'stock'                => 12,
                'stock_bajo'           => 4,
                'url_imagen'           => 'https://i.ibb.co/4gVsk9hp/image.png',
                'marca'                => 'Atari',
                'consola'              => '2600',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Sega Master System',
                'descripcion'          => 'Consola de 8 bits de Sega.',
                'precio_original'      => 130000.00,
                'precio'               => 100000.00,
                'porcentaje_descuento' => 23,
                'stock'                => 7,
                'stock_bajo'           => 3,
                'url_imagen'           => 'https://i.ibb.co/S74SyXhM/image.png',
                'marca'                => 'Sega',
                'consola'              => 'Master System',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'GameCube',
                'descripcion'          => 'Consola con forma de cubo de Nintendo.',
                'precio_original'      => 160000.00,
                'precio'               => 130000.00,
                'porcentaje_descuento' => 18,
                'stock'                => 14,
                'stock_bajo'           => 5,
                'url_imagen'           => 'https://i.ibb.co/QvwRzxkT/image.png',
                'marca'                => 'Nintendo',
                'consola'              => 'GameCube',
                'condicion'            => 'usado',
            ],
        ];

        foreach ($consolas as $consola) {
            DB::table('productos')->insert([
                ...$consola,
                'tipo_producto' => 'consola',
                'activo'        => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ]);
        }

        // ─────────────────────────────────────────────
        //  PRODUCTOS — ACCESORIOS (Normalizados a ARS y reasignados de categoría)
        // ─────────────────────────────────────────────
        $accesorios = [
            [
                'id_categoria'         => 8,
                'nombre'               => 'Mando Original N64',
                'descripcion'          => 'Mando original para Nintendo 64 en color gris.',
                'precio_original'      => 40000.00,
                'precio'               => 35000.00,
                'porcentaje_descuento' => 13,
                'stock'                => 15,
                'stock_bajo'           => 5,
                'url_imagen'           => 'https://i.ibb.co/jP5ChNYk/image.png',
                'marca'                => 'Nintendo',
                'consola'              => 'Nintendo 64',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Memory Card 8MB PS2',
                'descripcion'          => 'Tarjeta de memoria original de 8MB para PlayStation 2.',
                'precio_original'      => 15000.00,
                'precio'               => 15000.00,
                'porcentaje_descuento' => 0,
                'stock'                => 30,
                'stock_bajo'           => 10,
                'url_imagen'           => 'https://i.ibb.co/Txvgh7CP/image.png',
                'marca'                => 'Sony',
                'consola'              => 'PlayStation 2',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Guitarra Guitar Hero',
                'descripcion'          => 'Controlador de guitarra para Guitar Hero en PS2.',
                'precio_original'      => 60000.00,
                'precio'               => 50000.00,
                'porcentaje_descuento' => 17,
                'stock'                => 5,
                'stock_bajo'           => 2,
                'url_imagen'           => 'https://i.ibb.co/C5CRKYDW/image.png',
                'marca'                => 'RedOctane',
                'consola'              => 'PlayStation 2',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Volante y Control de Movimiento para Nintendo Wii',
                'descripcion'          => 'Accesorio de volante para Wii Remote.',
                'precio_original'      => 20000.00,
                'precio'               => 18000.00,
                'porcentaje_descuento' => 10,
                'stock'                => 20,
                'stock_bajo'           => 5,
                'url_imagen'           => 'https://i.ibb.co/nM6Rtj8v/image.png',
                'marca'                => 'Nintendo',
                'consola'              => 'Wii',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Multitap PS1',
                'descripcion'          => 'Adaptador para conectar hasta 4 mandos en PlayStation 1.',
                'precio_original'      => 25000.00,
                'precio'               => 20000.00,
                'porcentaje_descuento' => 20,
                'stock'                => 8,
                'stock_bajo'           => 3,
                'url_imagen'           => 'https://i.ibb.co/HRKrvLS/image.png',
                'marca'                => 'Sony',
                'consola'              => 'PlayStation 1',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Rumble Pak N64',
                'descripcion'          => 'Accesorio de vibración para el mando de Nintendo 64.',
                'precio_original'      => 30000.00,
                'precio'               => 25000.00,
                'porcentaje_descuento' => 17,
                'stock'                => 12,
                'stock_bajo'           => 4,
                'url_imagen'           => 'https://i.ibb.co/5WfrjpR2/image.png',
                'marca'                => 'Nintendo',
                'consola'              => 'Nintendo 64',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Cable Link GBA',
                'descripcion'          => 'Cable para conectar dos consolas Game Boy Advance.',
                'precio_original'      => 15000.00,
                'precio'               => 12000.00,
                'porcentaje_descuento' => 20,
                'stock'                => 25,
                'stock_bajo'           => 10,
                'url_imagen'           => 'https://i.ibb.co/GQdX1xNh/image.png',
                'marca'                => 'Nintendo',
                'consola'              => 'Game Boy Advance',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Zapper NES',
                'descripcion'          => 'Pistola de luz original para Nintendo Entertainment System.',
                'precio_original'      => 45000.00,
                'precio'               => 40000.00,
                'porcentaje_descuento' => 11,
                'stock'                => 4,
                'stock_bajo'           => 1,
                'url_imagen'           => 'https://i.ibb.co/ccjzwHMn/image.png',
                'marca'                => 'Nintendo',
                'consola'              => 'NES',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Mando Arcade Genesis',
                'descripcion'          => 'Mando tipo arcade de 6 botones para Sega Genesis.',
                'precio_original'      => 35000.00,
                'precio'               => 30000.00,
                'porcentaje_descuento' => 14,
                'stock'                => 10,
                'stock_bajo'           => 3,
                'url_imagen'           => 'https://i.ibb.co/6cmY6x4b/image.png',
                'marca'                => 'Sega',
                'consola'              => 'Sega Genesis',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Memory Card 1MB PS1',
                'descripcion'          => 'Tarjeta de memoria original de 1MB para PlayStation 1.',
                'precio_original'      => 12000.00,
                'precio'               => 10000.00,
                'porcentaje_descuento' => 17,
                'stock'                => 40,
                'stock_bajo'           => 15,
                'url_imagen'           => 'https://i.ibb.co/rKhXVTS5/image.png',
                'marca'                => 'Sony',
                'consola'              => 'PlayStation 1',
                'condicion'            => 'usado',
            ],
        ];

        foreach ($accesorios as $accesorio) {
            DB::table('productos')->insert([
                ...$accesorio,
                'tipo_producto' => 'periferico',
                'activo'        => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ]);
        }
    }
}