<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $now = Carbon::now();

        // ─────────────────────────────────────────────
        //  USUARIOS
        // ─────────────────────────────────────────────
        User::firstOrCreate(
            ['email' => 'admin@gmail.com'],
            [
                'nombre'   => 'Juan Pérez',
                'password' => bcrypt('admin123'),
                'rol'      => 'ADMIN',
                'activo'   => true,
            ]
        );

        // ─────────────────────────────────────────────
        //  CATEGORÍAS
        // ─────────────────────────────────────────────
        $categorias = [
            ['id' => 1,  'nombre' => 'RPG',             'descripcion' => 'Juegos de rol'],
            ['id' => 2,  'nombre' => 'Plataformas',     'descripcion' => 'Juegos de plataformas'],
            ['id' => 3,  'nombre' => 'Survival Horror', 'descripcion' => 'Juegos de terror y supervivencia'],
            ['id' => 4,  'nombre' => 'Carreras',        'descripcion' => 'Juegos de carreras'],
            ['id' => 5,  'nombre' => 'Deportes',        'descripcion' => 'Juegos deportivos'],
            ['id' => 6,  'nombre' => 'Estrategia',      'descripcion' => 'Juegos de estrategia'],
            ['id' => 7,  'nombre' => 'Lucha',           'descripcion' => 'Juegos de lucha'],
            ['id' => 8,  'nombre' => 'Aventura',        'descripcion' => 'Juegos de aventura'],
            ['id' => 9,  'nombre' => 'Puzzle',          'descripcion' => 'Juegos de puzzle'],
            ['id' => 10, 'nombre' => 'Periféricos',     'descripcion' => 'Accesorios y periféricos para consolas'],
        ];

        foreach ($categorias as $cat) {
            DB::table('categorias')->insert([
                ...$cat,
                'activo'     => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ]);
        }

        // ─────────────────────────────────────────────
        //  PRODUCTOS — JUEGOS
        // ─────────────────────────────────────────────
        $juegos = [
            [
                'id_categoria'         => 3,
                'nombre'               => 'Resident Evil Director\'s Cut',
                'descripcion'          => 'Videojuego survival horror.',
                'precio_original'      => 169000.00,
                'precio'               => 143650.00,
                'porcentaje_descuento' => 15,
                'stock'                => 3,
                'stock_bajo'           => 1,
                'url_imagen'           => 're_dc.jpg',
                'marca'                => 'Capcom',
                'consola'              => 'PS1',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Metal Gear Solid 1',
                'descripcion'          => 'Videojuego de acción y aventura.',
                'precio_original'      => 100000.00,
                'precio'               => 70000.00,
                'porcentaje_descuento' => 30,
                'stock'                => 2,
                'stock_bajo'           => 1,
                'url_imagen'           => 'mgs1.jpg',
                'marca'                => 'Konami',
                'consola'              => 'PS1',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'LSD Dream Emulator',
                'descripcion'          => 'Videojuego de exploración.',
                'precio_original'      => 95000.00,
                'precio'               => 80750.00,
                'porcentaje_descuento' => 15,
                'stock'                => 3,
                'stock_bajo'           => 1,
                'url_imagen'           => 'lsd_dream_emulator.jpg',
                'marca'                => 'Asmik Ace',
                'consola'              => 'PS1',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 3,
                'nombre'               => 'Silent Hill 2',
                'descripcion'          => 'Videojuego survival horror.',
                'precio_original'      => 110000.00,
                'precio'               => 77000.00,
                'porcentaje_descuento' => 30,
                'stock'                => 4,
                'stock_bajo'           => 1,
                'url_imagen'           => 'sh2_ps2.jpg',
                'marca'                => 'Konami',
                'consola'              => 'PS2',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 1,
                'nombre'               => 'Shin Megami Tensei Persona 4',
                'descripcion'          => 'Videojuego RPG.',
                'precio_original'      => 180000.00,
                'precio'               => 180000.00,
                'porcentaje_descuento' => 0,
                'stock'                => 5,
                'stock_bajo'           => 1,
                'url_imagen'           => 'persona3.jpg',
                'marca'                => 'Atlus',
                'consola'              => 'PS2',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Castlevania: Symphony of the Night',
                'descripcion'          => 'Videojuego de acción y aventura (Metroidvania).',
                'precio_original'      => 195000.00,
                'precio'               => 165750.00,
                'porcentaje_descuento' => 15,
                'stock'                => 6,
                'stock_bajo'           => 1,
                'url_imagen'           => 'cv_sotn.jpg',
                'marca'                => 'Konami',
                'consola'              => 'PS1',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Pokémon Rojo, Azul y Amarillo',
                'descripcion'          => 'Videojuego de aventura.',
                'precio_original'      => 55556.00,
                'precio'               => 50000.40,
                'porcentaje_descuento' => 10,
                'stock'                => 5,
                'stock_bajo'           => 1,
                'url_imagen'           => 'pokemon_raa.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'GameBoy',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'God of War',
                'descripcion'          => 'Videojuego de acción y aventura.',
                'precio_original'      => 55000.00,
                'precio'               => 41250.00,
                'porcentaje_descuento' => 25,
                'stock'                => 9,
                'stock_bajo'           => 1,
                'url_imagen'           => 'god_of_war.jpg',
                'marca'                => 'Sony',
                'consola'              => 'PS2',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Devil May Cry',
                'descripcion'          => 'Videojuego hack and slash.',
                'precio_original'      => 105000.00,
                'precio'               => 105000.00,
                'porcentaje_descuento' => 0,
                'stock'                => 8,
                'stock_bajo'           => 1,
                'url_imagen'           => 'dmc_ps2.jpg',
                'marca'                => 'Capcom',
                'consola'              => 'PS2',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Star Wars Lethal Alliance',
                'descripcion'          => 'Videojuego de acción y aventura.',
                'precio_original'      => 14900.00,
                'precio'               => 10430.00,
                'porcentaje_descuento' => 30,
                'stock'                => 8,
                'stock_bajo'           => 1,
                'url_imagen'           => 'sw_la.jpg',
                'marca'                => 'Ubisoft',
                'consola'              => 'Nintendo DS',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 4,
                'nombre'               => 'Gran Turismo 4',
                'descripcion'          => 'Juego de carreras de autos.',
                'precio_original'      => 15000.00,
                'precio'               => 11250.00,
                'porcentaje_descuento' => 25,
                'stock'                => 10,
                'stock_bajo'           => 1,
                'url_imagen'           => 'gt4.jpg',
                'marca'                => 'Sony',
                'consola'              => 'PS2',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 1,
                'nombre'               => 'EverGrace',
                'descripcion'          => 'Juego RPG.',
                'precio_original'      => 12000.00,
                'precio'               => 9000.00,
                'porcentaje_descuento' => 25,
                'stock'                => 4,
                'stock_bajo'           => 1,
                'url_imagen'           => 'evergrace_ps2.jpg',
                'marca'                => 'FromSoftware',
                'consola'              => 'PS2',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 1,
                'nombre'               => 'Chrono Trigger',
                'descripcion'          => 'Juego RPG.',
                'precio_original'      => 120000.00,
                'precio'               => 90000.00,
                'porcentaje_descuento' => 25,
                'stock'                => 10,
                'stock_bajo'           => 1,
                'url_imagen'           => 'chrono_trigger_box_art.jpg',
                'marca'                => 'Square',
                'consola'              => 'SNES',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 1,
                'nombre'               => 'Parasite Eve',
                'descripcion'          => 'Videojuego de rol.',
                'precio_original'      => 45000.00,
                'precio'               => 38250.00,
                'porcentaje_descuento' => 15,
                'stock'                => 4,
                'stock_bajo'           => 1,
                'url_imagen'           => 'sh2_strange_photo.jpg',
                'marca'                => 'Square',
                'consola'              => 'PS1',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 1,
                'nombre'               => 'Mega Man Battle Network',
                'descripcion'          => 'Videojuego de rol.',
                'precio_original'      => 50000.00,
                'precio'               => 45000.00,
                'porcentaje_descuento' => 10,
                'stock'                => 5,
                'stock_bajo'           => 1,
                'url_imagen'           => 'mmbn.jpg',
                'marca'                => 'Capcom',
                'consola'              => 'Gameboy Advance',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Super Metroid',
                'descripcion'          => 'Videojuego de acción y aventura.',
                'precio_original'      => 80000.00,
                'precio'               => 72000.00,
                'porcentaje_descuento' => 10,
                'stock'                => 3,
                'stock_bajo'           => 1,
                'url_imagen'           => 'super_metroid_snes.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'SNES',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 2,
                'nombre'               => 'Super Mario 64',
                'descripcion'          => 'Juego de plataformas.',
                'precio_original'      => 165000.00,
                'precio'               => 148500.00,
                'porcentaje_descuento' => 10,
                'stock'                => 5,
                'stock_bajo'           => 1,
                'url_imagen'           => 'super_mario_64.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'Nintendo 64',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 3,
                'nombre'               => 'Silent Hill 3',
                'descripcion'          => 'Juego de survival horror.',
                'precio_original'      => 145000.00,
                'precio'               => 116000.00,
                'porcentaje_descuento' => 20,
                'stock'                => 5,
                'stock_bajo'           => 1,
                'url_imagen'           => 'silent_hill_3.jpg',
                'marca'                => 'Konami',
                'consola'              => 'PS2',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'The Legend of Zelda: Ocarina of Time',
                'descripcion'          => 'Videojuego de acción y aventura.',
                'precio_original'      => 150000.00,
                'precio'               => 150000.00,
                'porcentaje_descuento' => 0,
                'stock'                => 4,
                'stock_bajo'           => 1,
                'url_imagen'           => 'zelda_oot.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'Nintendo 64',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 1,
                'nombre'               => 'Final Fantasy VII',
                'descripcion'          => 'Videojuego de rol.',
                'precio_original'      => 120000.00,
                'precio'               => 102000.00,
                'porcentaje_descuento' => 15,
                'stock'                => 6,
                'stock_bajo'           => 1,
                'url_imagen'           => 'ff7.jpg',
                'marca'                => 'Square',
                'consola'              => 'PS1',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 2,
                'nombre'               => 'Sonic the Hedgehog 2',
                'descripcion'          => 'Videojuego de plataformas.',
                'precio_original'      => 40000.00,
                'precio'               => 36000.00,
                'porcentaje_descuento' => 10,
                'stock'                => 8,
                'stock_bajo'           => 1,
                'url_imagen'           => 'sonic2.jpg',
                'marca'                => 'Sega',
                'consola'              => 'Sega Genesis',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 2,
                'nombre'               => 'Crash Bandicoot',
                'descripcion'          => 'Videojuego de plataformas.',
                'precio_original'      => 90000.00,
                'precio'               => 81000.00,
                'porcentaje_descuento' => 10,
                'stock'                => 5,
                'stock_bajo'           => 1,
                'url_imagen'           => 'crash_bandicoot.jpg',
                'marca'                => 'Naughty Dog',
                'consola'              => 'PS1',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 7,
                'nombre'               => 'Street Fighter II',
                'descripcion'          => 'Videojuego de lucha.',
                'precio_original'      => 50000.00,
                'precio'               => 45000.00,
                'porcentaje_descuento' => 10,
                'stock'                => 7,
                'stock_bajo'           => 1,
                'url_imagen'           => 'sf2.jpg',
                'marca'                => 'Capcom',
                'consola'              => 'SNES',
                'condicion'            => 'usado',
            ],
        ];

        foreach ($juegos as $juego) {
            DB::table('productos')->insert([
                ...$juego,
                'tipo_producto' => 'videojuego',
                'activo'        => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ]);
        }

        // ─────────────────────────────────────────────
        //  PRODUCTOS — CONSOLAS
        // ─────────────────────────────────────────────
        $consolas = [
            [
                'id_categoria'         => 8,
                'nombre'               => 'Nintendo Entertainment System',
                'descripcion'          => 'Consola clásica de 8 bits.',
                'precio_original'      => 100.00,
                'precio'               => 80.00,
                'porcentaje_descuento' => 20,
                'stock'                => 15,
                'stock_bajo'           => 5,
                'url_imagen'           => 'nes.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'NES',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Super Nintendo',
                'descripcion'          => 'Consola de 16 bits de Nintendo.',
                'precio_original'      => 150.00,
                'precio'               => 120.00,
                'porcentaje_descuento' => 20,
                'stock'                => 10,
                'stock_bajo'           => 3,
                'url_imagen'           => 'snes.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'SNES',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Sega Genesis',
                'descripcion'          => 'Consola de 16 bits de Sega.',
                'precio_original'      => 120.00,
                'precio'               => 90.00,
                'porcentaje_descuento' => 25,
                'stock'                => 20,
                'stock_bajo'           => 5,
                'url_imagen'           => 'genesis.jpg',
                'marca'                => 'Sega',
                'consola'              => 'Sega Genesis',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'PlayStation 1',
                'descripcion'          => 'Primera consola de Sony.',
                'precio_original'      => 80.00,
                'precio'               => 60.00,
                'porcentaje_descuento' => 25,
                'stock'                => 30,
                'stock_bajo'           => 10,
                'url_imagen'           => 'ps1.jpg',
                'marca'                => 'Sony',
                'consola'              => 'PS1',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Nintendo 64',
                'descripcion'          => 'Consola de 64 bits de Nintendo.',
                'precio_original'      => 180.00,
                'precio'               => 150.00,
                'porcentaje_descuento' => 16,
                'stock'                => 8,
                'stock_bajo'           => 2,
                'url_imagen'           => 'n64.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'N64',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Sega Dreamcast',
                'descripcion'          => 'Última consola de Sega.',
                'precio_original'      => 200.00,
                'precio'               => 160.00,
                'porcentaje_descuento' => 20,
                'stock'                => 5,
                'stock_bajo'           => 2,
                'url_imagen'           => 'dreamcast.jpg',
                'marca'                => 'Sega',
                'consola'              => 'Dreamcast',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Game Boy',
                'descripcion'          => 'Consola portátil de Nintendo.',
                'precio_original'      => 90.00,
                'precio'               => 70.00,
                'porcentaje_descuento' => 22,
                'stock'                => 25,
                'stock_bajo'           => 8,
                'url_imagen'           => 'gameboy.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'Game Boy',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Atari 2600',
                'descripcion'          => 'Pionera en consolas de videojuegos.',
                'precio_original'      => 110.00,
                'precio'               => 85.00,
                'porcentaje_descuento' => 22,
                'stock'                => 12,
                'stock_bajo'           => 4,
                'url_imagen'           => 'atari.jpg',
                'marca'                => 'Atari',
                'consola'              => '2600',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'Sega Master System',
                'descripcion'          => 'Consola de 8 bits de Sega.',
                'precio_original'      => 130.00,
                'precio'               => 100.00,
                'porcentaje_descuento' => 23,
                'stock'                => 7,
                'stock_bajo'           => 3,
                'url_imagen'           => 'mastersystem.jpg',
                'marca'                => 'Sega',
                'consola'              => 'Master System',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 8,
                'nombre'               => 'GameCube',
                'descripcion'          => 'Consola con forma de cubo de Nintendo.',
                'precio_original'      => 160.00,
                'precio'               => 130.00,
                'porcentaje_descuento' => 18,
                'stock'                => 14,
                'stock_bajo'           => 5,
                'url_imagen'           => 'gamecube.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'GameCube',
                'condicion'            => 'usado',
            ],
        ];

        foreach ($consolas as $consola) {
            DB::table('productos')->insert([
                ...$consola,
                'tipo_producto' => 'consola',
                'activo'        => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ]);
        }

        // ─────────────────────────────────────────────
        //  PRODUCTOS — ACCESORIOS  (id_categoria = 10 → Periféricos)
        // ─────────────────────────────────────────────
        $accesorios = [
            [
                'id_categoria'         => 10,
                'nombre'               => 'Mando Original N64',
                'descripcion'          => 'Mando original para Nintendo 64 en color gris.',
                'precio_original'      => 40.00,
                'precio'               => 35.00,
                'porcentaje_descuento' => 13,
                'stock'                => 15,
                'stock_bajo'           => 5,
                'url_imagen'           => 'mando_n64.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'Nintendo 64',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 10,
                'nombre'               => 'Memory Card 8MB PS2',
                'descripcion'          => 'Tarjeta de memoria original de 8MB para PlayStation 2.',
                'precio_original'      => 15.00,
                'precio'               => 15.00,
                'porcentaje_descuento' => 0,
                'stock'                => 30,
                'stock_bajo'           => 10,
                'url_imagen'           => 'memory_card_ps2.jpg',
                'marca'                => 'Sony',
                'consola'              => 'PlayStation 2',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 10,
                'nombre'               => 'Guitarra Guitar Hero',
                'descripcion'          => 'Controlador de guitarra para Guitar Hero en PS2.',
                'precio_original'      => 60.00,
                'precio'               => 50.00,
                'porcentaje_descuento' => 17,
                'stock'                => 5,
                'stock_bajo'           => 2,
                'url_imagen'           => 'guitarra_guitar_hero.jpg',
                'marca'                => 'RedOctane',
                'consola'              => 'PlayStation 2',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 10,
                'nombre'               => 'Volante Mario Kart',
                'descripcion'          => 'Accesorio de volante para Wii Remote.',
                'precio_original'      => 20.00,
                'precio'               => 18.00,
                'porcentaje_descuento' => 10,
                'stock'                => 20,
                'stock_bajo'           => 5,
                'url_imagen'           => 'volante_mario_kart.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'Wii',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 10,
                'nombre'               => 'Multitap PS1',
                'descripcion'          => 'Adaptador para conectar hasta 4 mandos en PlayStation 1.',
                'precio_original'      => 25.00,
                'precio'               => 20.00,
                'porcentaje_descuento' => 20,
                'stock'                => 8,
                'stock_bajo'           => 3,
                'url_imagen'           => 'multitap_ps1.jpg',
                'marca'                => 'Sony',
                'consola'              => 'PlayStation 1',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 10,
                'nombre'               => 'Rumble Pak N64',
                'descripcion'          => 'Accesorio de vibración para el mando de Nintendo 64.',
                'precio_original'      => 30.00,
                'precio'               => 25.00,
                'porcentaje_descuento' => 17,
                'stock'                => 12,
                'stock_bajo'           => 4,
                'url_imagen'           => 'rumble_pak_n64.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'Nintendo 64',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 10,
                'nombre'               => 'Cable Link GBA',
                'descripcion'          => 'Cable para conectar dos consolas Game Boy Advance.',
                'precio_original'      => 15.00,
                'precio'               => 12.00,
                'porcentaje_descuento' => 20,
                'stock'                => 25,
                'stock_bajo'           => 10,
                'url_imagen'           => 'cable_link_gba.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'Game Boy Advance',
                'condicion'            => 'nuevo',
            ],
            [
                'id_categoria'         => 10,
                'nombre'               => 'Zapper NES',
                'descripcion'          => 'Pistola de luz original para Nintendo Entertainment System.',
                'precio_original'      => 45.00,
                'precio'               => 40.00,
                'porcentaje_descuento' => 11,
                'stock'                => 4,
                'stock_bajo'           => 1,
                'url_imagen'           => 'zapper_nes.jpg',
                'marca'                => 'Nintendo',
                'consola'              => 'NES',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 10,
                'nombre'               => 'Mando Arcade Genesis',
                'descripcion'          => 'Mando tipo arcade de 6 botones para Sega Genesis.',
                'precio_original'      => 35.00,
                'precio'               => 30.00,
                'porcentaje_descuento' => 14,
                'stock'                => 10,
                'stock_bajo'           => 3,
                'url_imagen'           => 'mando_arcade_genesis.jpg',
                'marca'                => 'Sega',
                'consola'              => 'Sega Genesis',
                'condicion'            => 'usado',
            ],
            [
                'id_categoria'         => 10,
                'nombre'               => 'Memory Card 1MB PS1',
                'descripcion'          => 'Tarjeta de memoria original de 1MB para PlayStation 1.',
                'precio_original'      => 12.00,
                'precio'               => 10.00,
                'porcentaje_descuento' => 17,
                'stock'                => 40,
                'stock_bajo'           => 15,
                'url_imagen'           => 'memory_card_ps1.jpg',
                'marca'                => 'Sony',
                'consola'              => 'PlayStation 1',
                'condicion'            => 'usado',
            ],
        ];

        foreach ($accesorios as $accesorio) {
            DB::table('productos')->insert([
                ...$accesorio,
                'tipo_producto' => 'periferico',
                'activo'        => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ]);
        }
    }
}